/**
 * MCP page.
 *
 * Informational and diagnostic. The real MCP server is a separate process
 * speaking stdio, so this page reports its configuration and the tools it
 * exposes rather than pretending to be it — the tool list is derived from the
 * same connector action registry the adapter iterates, which is exactly why
 * the two cannot disagree.
 */

import { Check, Copy, Network, Terminal } from 'lucide-react';
import { useState } from 'react';
import {
  AsyncBoundary,
  Button,
  PageHeader,
  Panel,
  PanelHeader,
  StatusPill,
  TableSkeleton,
} from '@/components/ui';
import { useActions, useStatus } from '@/hooks/useConnector';
import { copyToClipboard } from '@/lib/utils';

const CLAUDE_DESKTOP_CONFIG = `{
  "mcpServers": {
    "asana-connector": {
      "command": "npx",
      "args": ["tsx", "/ABSOLUTE/PATH/TO/doo-asana-connector/mcp/server.ts"]
    }
  }
}`;

/**
 * Claude Desktop speaks stdio, so a hosted endpoint is reached through
 * `mcp-remote`, which bridges the two and carries the bearer token.
 */
const remoteConfig = (url: string): string => `{
  "mcpServers": {
    "asana-connector": {
      "command": "npx",
      "args": [
        "mcp-remote", "${url}",
        "--header", "Authorization: Bearer \${MCP_AUTH_TOKEN}"
      ],
      "env": { "MCP_AUTH_TOKEN": "<your token>" }
    }
  }
}`;

export function Mcp() {
  const status = useStatus();
  const actions = useActions();

  /*
   * The endpoint's address. PUBLIC_BASE_URL is the deployment stating its own
   * public origin; without it the console can only report where it was loaded
   * from, which is right locally and on the deployment itself but wrong
   * everywhere else — so which one is being shown is said out loud.
   */
  const configured = status.data?.config.mcp.publicUrl ?? null;
  const endpoint = configured ?? `${window.location.origin}/mcp`;
  const authRequired = status.data?.config.mcp.authRequired ?? false;

  return (
    <div className="mx-auto max-w-5xl">
      <PageHeader
        title="MCP"
        description="Model Context Protocol adapter — a thin wrapper that exposes the connector's actions as MCP tools."
      />

      {/* Status */}
      <div className="mb-4 grid gap-3 sm:grid-cols-3">
        <Panel className="p-4">
          <div className="flex items-center justify-between">
            <span className="text-xs text-(--color-ink-muted)">Transport</span>
            <StatusPill tone="success">Ready</StatusPill>
          </div>
          <p className="mt-2 text-lg font-semibold uppercase text-(--color-ink)">
            {status.data?.config.mcp.transport ?? '—'}
          </p>
          <p className="mt-0.5 text-xs text-(--color-ink-subtle)">
            {status.data?.config.mcp.transport === 'http'
              ? `Streamable HTTP on :${status.data.config.mcp.httpPort}/mcp`
              : 'Local stdio — for Claude Desktop and MCP Inspector'}
          </p>
        </Panel>

        <Panel className="p-4">
          <div className="flex items-center justify-between">
            <span className="text-xs text-(--color-ink-muted)">Tools exposed</span>
            <StatusPill tone="info">Derived</StatusPill>
          </div>
          <p className="mt-2 text-lg font-semibold text-(--color-ink)">
            {actions.data?.actions.length ?? '—'}
          </p>
          <p className="mt-0.5 text-xs text-(--color-ink-subtle)">
            One per connector action, generated by iteration
          </p>
        </Panel>

        <Panel className="p-4">
          <div className="flex items-center justify-between">
            <span className="text-xs text-(--color-ink-muted)">Adapter</span>
            <StatusPill tone="success">Thin</StatusPill>
          </div>
          <p className="mt-2 text-lg font-semibold text-(--color-ink)">0</p>
          <p className="mt-0.5 text-xs text-(--color-ink-subtle)">
            Asana calls inside the adapter — enforced by test
          </p>
        </Panel>
      </div>

      {/* The endpoint, under the status strip: what it is, then where it is. */}
      <Panel className="mb-4">
        <PanelHeader
          title="Endpoint"
          description="Streamable HTTP. Point any MCP client at this URL — it is the same adapter, over the same connector actions."
        />
        <div className="space-y-4 p-4">
          <div>
            <div className="mb-1.5 flex flex-wrap items-center gap-2">
              <p className="text-xs font-medium text-(--color-ink)">MCP URL</p>
              <StatusPill tone={configured === null ? 'warning' : 'success'}>
                {configured === null ? 'From this origin' : 'Configured'}
              </StatusPill>
              <StatusPill tone={authRequired ? 'success' : 'danger'}>
                {authRequired ? 'Bearer token required' : 'No token set'}
              </StatusPill>
            </div>
            <CodeBlock code={endpoint} />
            <p className="mt-1.5 text-[11px] text-(--color-ink-subtle)">
              {configured === null ? (
                <>
                  Nothing is configured, so this is the origin the console was loaded from. Set{' '}
                  <code className="mono">PUBLIC_BASE_URL</code> on the deployment to publish its real
                  address here.
                </>
              ) : (
                <>
                  From <code className="mono">PUBLIC_BASE_URL</code> on the deployment. Liveness is
                  at <code className="mono">{`${endpoint}/health`}</code> and needs no credential.
                </>
              )}
            </p>
            {authRequired ? null : (
              <p className="mt-1.5 text-[11px] text-(--color-warning)">
                <code className="mono">MCP_AUTH_TOKEN</code> is unset, so this endpoint is open. It
                executes real actions with the server&apos;s credential — set one before leaving it
                reachable.
              </p>
            )}
          </div>

          <CommandBlock
            label="Try it"
            command={`curl -X POST ${endpoint} \\
  -H 'Authorization: Bearer <token>' \\
  -H 'Content-Type: application/json' \\
  -H 'Accept: application/json, text/event-stream' \\
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'`}
            note="Lists the tools. Both Accept types are required by the Streamable HTTP transport."
          />

          <CommandBlock
            label="Open in the MCP Inspector"
            command={`npx @modelcontextprotocol/inspector ${endpoint}`}
            note="Browse and call the tools by hand against the hosted endpoint."
          />

          <div>
            <p className="mb-1.5 text-xs font-medium text-(--color-ink)">
              Claude Desktop, against this endpoint
            </p>
            <p className="mb-2 text-[11px] text-(--color-ink-subtle)">
              Claude Desktop speaks stdio, so <code className="mono">mcp-remote</code> bridges it to
              the hosted URL and carries the token.
            </p>
            <CodeBlock code={remoteConfig(endpoint)} />
          </div>
        </div>
      </Panel>

      {/* How to run */}
      <Panel className="mb-4">
        <PanelHeader
          title="Running the MCP server"
          description="The adapter is a separate process. It is not started by this console."
        />
        <div className="space-y-4 p-4">
          <CommandBlock
            label="Start over stdio"
            command="npm run mcp"
            note="What Claude Desktop and other local MCP clients use."
          />
          <CommandBlock
            label="Inspect interactively"
            command="npm run mcp:inspect"
            note="Opens the MCP Inspector so you can list and call tools by hand."
          />
          <CommandBlock
            label="Start over Streamable HTTP"
            command="MCP_TRANSPORT=http npm run mcp"
            note="For a deployed endpoint. Terminate TLS at your platform's proxy."
          />

          <div>
            <p className="mb-1.5 text-xs font-medium text-(--color-ink)">
              Claude Desktop configuration
            </p>
            <p className="mb-2 text-[11px] text-(--color-ink-subtle)">
              Add to <code className="mono">claude_desktop_config.json</code>, replacing the path
              with this project&apos;s absolute location.
            </p>
            <CodeBlock code={CLAUDE_DESKTOP_CONFIG} />
          </div>
        </div>
      </Panel>

      {/* Tools */}
      <Panel>
        <PanelHeader
          title="Available tools"
          description="Generated from the connector action registry. A test asserts this list equals the connector's actions."
        />

        <AsyncBoundary
          isLoading={actions.isLoading}
          error={actions.error}
          data={actions.data}
          loadingFallback={<TableSkeleton rows={5} columns={3} />}
          onRetry={() => void actions.refetch()}
        >
          {(data) => (
            <ul className="divide-y divide-(--color-hairline)">
              {data.actions.map((action) => (
                <li key={action.id} className="p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <Network className="h-3.5 w-3.5 text-(--color-ink-subtle)" aria-hidden="true" />
                    {/* MCP tool names replace dots with underscores. */}
                    <code className="mono text-(--color-ink)">{action.id.replace(/\./g, '_')}</code>
                    <StatusPill tone={action.type === 'write' ? 'warning' : 'info'}>
                      {action.type === 'write' ? 'readOnlyHint: false' : 'readOnlyHint: true'}
                    </StatusPill>
                    <StatusPill tone={action.safety.idempotent ? 'success' : 'danger'}>
                      idempotentHint: {String(action.safety.idempotent)}
                    </StatusPill>
                    <StatusPill tone="neutral">destructiveHint: false</StatusPill>
                  </div>

                  <p className="mt-1.5 text-xs text-(--color-ink-muted)">{action.description}</p>

                  {action.safety.requiresApproval ? (
                    <p className="mt-1.5 text-[11px] text-(--color-warning)">
                      Requires <code className="mono">approved: true</code> — so a model exploring
                      the tool list cannot write to Asana as a side effect.
                    </p>
                  ) : null}
                </li>
              ))}
            </ul>
          )}
        </AsyncBoundary>
      </Panel>
    </div>
  );
}

function CommandBlock({ label, command, note }: { label: string; command: string; note: string }) {
  return (
    <div>
      <p className="mb-1 text-xs font-medium text-(--color-ink)">{label}</p>
      <CodeBlock code={command} />
      <p className="mt-1 text-[11px] text-(--color-ink-subtle)">{note}</p>
    </div>
  );
}

function CodeBlock({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  return (
    <div className="relative">
      <pre className="mono overflow-x-auto rounded-(--radius-md) border border-(--color-hairline) bg-(--color-canvas) p-3 pr-20 text-(--color-ink)">
        {code}
      </pre>
      <div className="absolute right-2 top-2">
        <Button
          size="sm"
          icon={copied ? Check : Copy}
          onClick={() => {
            void copyToClipboard(code).then((ok) => {
              if (!ok) return;
              setCopied(true);
              setTimeout(() => setCopied(false), 1800);
            });
          }}
        >
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <Terminal className="sr-only" aria-hidden="true" />
    </div>
  );
}
